#!/usr/bin/env python3
"""
labmate.tools · Panel Designer — rebuild cytometry-data.js from cytometry-data.json.

Edit cytometry-data.json (add an instrument preset or a fluor, fix a value), then run:

    python build_data.py

The page loads cytometry-data.js as a plain <script>, so it also works when the
page is opened straight from disk.
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent


def main():
    d = json.loads((HERE / "cytometry-data.json").read_text(encoding="utf-8"))
    for f in d["fluors"]:
        for k in ("origin", "spectrum"):
            f.pop(k, None)
    for i in d["instruments"]:
        i.pop("origin", None)
    ids = [f["id"] for f in d["fluors"]]
    dup = sorted({x for x in ids if ids.count(x) > 1})
    if dup:
        raise SystemExit("Duplicate fluor ids: " + ", ".join(dup))
    out = {
        "schemaVersion": d.get("schemaVersion", 2),
        "compiled": d["_meta"]["compiled"],
        "notes": d["_meta"]["notes"],
        "instruments": d["instruments"],
        "fluors": d["fluors"],
    }
    js = ("/* labmate.tools · Panel Designer seed data (generated by build_data.py from "
          "cytometry-data.json — edit that file, not this one) */\n"
          "window.LMT_CYTO = " + json.dumps(out, ensure_ascii=False, separators=(",", ":")) + ";\n")
    (HERE / "cytometry-data.js").write_text(js, encoding="utf-8")
    print(f"Wrote cytometry-data.js: {len(d['instruments'])} instruments, {len(d['fluors'])} fluors.")


if __name__ == "__main__":
    main()
